### ISSUE TITLE
Windows failures require a tiny fix in test-suite

### ISSUE THREAD

**Issue by yarikoptic** [brechtm/citeproc-py#118]
Filed a PR there https://github.com/citation-style-language/test-suite/pull/47  but the question is what to do about it here.

- skip that testing on windows (not good IMHO)
- if that PR is merged not to progress forward test-suite (see #116), then we might need to use "our own" fork of the test-suite

WDYT @brechtm ?

**Comment by yarikoptic** [comment]
FWIW, fix was merged, so if we upgrade to current tip there -- we should be all set.  bisecting fresh failing tests though is an effort I ain't ready to commit to ATM.

**Comment by yarikoptic** [comment]
wild and not good idea : we can easily establish a list of commits to cherry pick via `git cherrypick` on top of the prestine clone but that would complicate comparison of "up to dateness"

**Comment by brechtm** [comment]
New failing test are OK if they have been added to the test suite since we last updated the test suite. To find out which tests were added, you can do:

    git diff --name-status --find-renames 5779a8cd6e2560ef28e5b72225ec15368b089084..HEAD | grep "^A"

Now, removing all these from the list of new failing tests, leaves only a handful. Searching these in the full diff:

    git diff --name-status --find-renames 5779a8cd6e2560ef28e5b72225ec15368b089084..HEAD

shows that all of these are in fact existing tests that were renamed, some of which were in the list of known failing tests:

```
date_SeasonRange1                               renamed from date_RawSeasonRange1
date_SeasonRange2                               renamed from date_RawSeasonRange2
date_SeasonRange3                               renamed from date_RawSeasonRange3
disambiguate_BasedOnSubsequentFormWithBackref2  renamed from disambiguate_BasedOnSubsequentFormWithBackref - already failing
label_PluralWithAmpersand                       renamed from position_NearNoteTrue - already failing
name_InTextMarkupNormalizeInitials              renamed from sort_BibliographyNosortOption - already failing
substitute_SubstituteOnlyOnceString             renamed from date_LoneJapaneseMonth
substitute_SubstituteOnlyOnceTerm               renamed from name_StaticParticles
substitute_SubstituteOnlyOnceVariable           renamed from variables_TitleShortOnAbbrevWithTitle - already failing
```

So we should really only need to have a closer look at the 5 newly failing tests. Still, it wouldn't hurt to see how the other 4 tests changed and if they are failing in a different way.

**Comment by brechtm** [comment]
On closer inspection, I shouldn't have blindly trusted git rename detection. only 3 of the failing tests are actually renamed, and their results were actually ignored (because they test citeproc-js features). The others are new tests:

```
date_SeasonRange1                               renamed from date_RawSeasonRange1 - ignored
date_SeasonRange2                               renamed from date_RawSeasonRange2 - ignored
date_SeasonRange3                               renamed from date_RawSeasonRange3 - ignored
disambiguate_BasedOnSubsequentFormWithBackref2  new test
label_PluralWithAmpersand                       new test
name_InTextMarkupNormalizeInitials              new test
substitute_SubstituteOnlyOnceString             new test
substitute_SubstituteOnlyOnceTerm               new test
substitute_SubstituteOnlyOnceVariable           new test
```

So I think it should be ok to update to the current test suite. only `IGNORED_RESULTS` needs to be adjusted to:

```python
IGNORED_RESULS = {
    'date_Accessed': 'raw date',
    'date_LopsidedDataYearSuffixCollapse': 'raw date',
    'date_RawParseSimpleDate': 'raw date',
    'date_SeasonRange1': 'raw date',
    'date_SeasonRange2': 'raw date',
    'date_SeasonRange3': 'raw date',
    'date_String': 'raw date',
}
```

**Comment by yarikoptic** [comment]
that is great.  If you are still in this mode and could push the changes to #115 - we might get close to reaching stable grounds there.  I will be able to test later on windows VM if any windows specific surprises come up

**Comment by brechtm** [comment]
These are tests whose changes now made them pass:

```
affix_PrefixFullCitationTextOnly
affix_WordProcessorAffixNoSpace
bugreports_ArabicLocale
bugreports_ChicagoAuthorDateLooping
bugreports_DelimiterOnLayout
bugreports_MissingItemInJoin
bugreports_NumberInMacroWithVerticalAlign
disambiguate_DisambiguateWithThree
disambiguate_DisambiguateWithThree2
disambiguate_ExtraTextCitation
group_LegalWithAuthorDate
```
